//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmitWinkel.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Appointment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Appointment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmitWinkel.Resources.Home.Appointment", typeof(Appointment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number (*).
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an Appointment
        ///
        ///Bold - Please complete the following fields to make an appointment. 
        ///
        ///We will contact you shortly to confirm the time and date of your appointment.
        ///
        ///Full Name (*)
        ///
        ///
        ///Surname (*)
        ///
        ///
        ///E-mail (*)
        ///
        ///
        ///Contact Number (*)
        ///
        ///
        ///How should we contact you?
        ///E-mailPhone
        ///
        ///Do you have medical aid or are you a private patient? (*)
        ///Medical AidPrivate
        ///
        ///When would you like to have an appointment? (*)
        ///
        ///
        ///Reason for your appointment / any additional information?.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (*).
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email2 {
            get {
                return ResourceManager.GetString("Email2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Names (*).
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an Appointment.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How should we contact you?.
        /// </summary>
        public static string HowShouldWeContact {
            get {
                return ResourceManager.GetString("HowShouldWeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Aid.
        /// </summary>
        public static string MedicalAid {
            get {
                return ResourceManager.GetString("MedicalAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have medical aid or are you a private patient? (*).
        /// </summary>
        public static string MedicalAidQuestion {
            get {
                return ResourceManager.GetString("MedicalAidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the following fields to make an appointment..
        /// </summary>
        public static string PleaseComplete {
            get {
                return ResourceManager.GetString("PleaseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for your appointment / any additional information?.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname (*).
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will contact you shortly to confirm the time and date of your appointment..
        /// </summary>
        public static string WeWillContact {
            get {
                return ResourceManager.GetString("WeWillContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When would you like to have an appointment? (*).
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
    }
}
