//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmitWinkel.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContactUs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactUs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmitWinkel.Resources.Home.ContactUs", typeof(ContactUs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Mountainview Drive, Bellville.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (after hours).
        /// </summary>
        internal static string AfterHours {
            get {
                return ResourceManager.GetString("AfterHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (by appointment only).
        /// </summary>
        internal static string ByAppointment {
            get {
                return ResourceManager.GetString("ByAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here and complete the form to make an appointment.
        /// </summary>
        internal static string ClickHereAppointment {
            get {
                return ResourceManager.GetString("ClickHereAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact numbers.
        /// </summary>
        internal static string ContactNumbers {
            get {
                return ResourceManager.GetString("ContactNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an Appointment
        ///Click here and complete the form to make an appointment
        ///Office Hours
        ///Monday-Friday:
        ///7h30-17h30
        ///
        ///Saturdays: 
        ///(by appointment only) 
        ///7h30-11h30
        ///Contact numbers
        ///Tel: 021 919 5559
        ///For emergencies 
        ///call: 083 444 5922     
        ///(after hours)
        ///
        ///Where are we?
        ///2 Mountainview Drive, Bellville 
        /// 
        ///
        ///View Map
        ///
        ///  
        ///Wheelchair Friendly
        ///
        ///Parking On-site!.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For emergencies.
        /// </summary>
        internal static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call: 083 444 5922.
        /// </summary>
        internal static string EmergencyNumber {
            get {
                return ResourceManager.GetString("EmergencyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an Appointment.
        /// </summary>
        internal static string MakeAppointment {
            get {
                return ResourceManager.GetString("MakeAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday-Friday:.
        /// </summary>
        internal static string MondayFriday {
            get {
                return ResourceManager.GetString("MondayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7h30-17h30.
        /// </summary>
        internal static string MonFriTimes {
            get {
                return ResourceManager.GetString("MonFriTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Hours.
        /// </summary>
        internal static string OfficeHours {
            get {
                return ResourceManager.GetString("OfficeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking On-site!.
        /// </summary>
        internal static string Parking {
            get {
                return ResourceManager.GetString("Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7h30-11h30.
        /// </summary>
        internal static string SatTimes {
            get {
                return ResourceManager.GetString("SatTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturdays:.
        /// </summary>
        internal static string Saturdays {
            get {
                return ResourceManager.GetString("Saturdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel: 021 919 5559.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Map.
        /// </summary>
        internal static string ViewMap {
            get {
                return ResourceManager.GetString("ViewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheelchair Friendly.
        /// </summary>
        internal static string Wheelchair {
            get {
                return ResourceManager.GetString("Wheelchair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are we?.
        /// </summary>
        internal static string WhereAreWe {
            get {
                return ResourceManager.GetString("WhereAreWe", resourceCulture);
            }
        }
    }
}
