//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmitWinkel.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmitWinkel.Resources.Home.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smit &amp; Winkel | Dental Surgeons.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel: 021 919 5559&lt;br/&gt;2 Mountainview Drive&lt;br/&gt;Bellville.
        /// </summary>
        public static string HeaderSubText {
            get {
                return ResourceManager.GetString("HeaderSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book an Appointment.
        /// </summary>
        public static string ImgBox1Header {
            get {
                return ResourceManager.GetString("ImgBox1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here and fill in the form to make an appointmen.
        /// </summary>
        public static string ImgBox1Text {
            get {
                return ResourceManager.GetString("ImgBox1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Patient?.
        /// </summary>
        public static string ImgBox2Header {
            get {
                return ResourceManager.GetString("ImgBox2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save some time and fill in a New Patient Registration Form online.
        /// </summary>
        public static string ImgBox2Text {
            get {
                return ResourceManager.GetString("ImgBox2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Hours.
        /// </summary>
        public static string ImgBox3Header {
            get {
                return ResourceManager.GetString("ImgBox3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday-Friday: 7h30-17h30&lt;br/&gt;Saturdays: (by appointment only) 7h30-11h30.
        /// </summary>
        public static string ImgBox3Text {
            get {
                return ResourceManager.GetString("ImgBox3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string NavLinkContactUs {
            get {
                return ResourceManager.GetString("NavLinkContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dental Service.
        /// </summary>
        public static string NavLinkDentalService {
            get {
                return ResourceManager.GetString("NavLinkDentalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavLinkHome {
            get {
                return ResourceManager.GetString("NavLinkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Patient.
        /// </summary>
        public static string NavLinkNewPatient {
            get {
                return ResourceManager.GetString("NavLinkNewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        public static string NavLinkOurTeam {
            get {
                return ResourceManager.GetString("NavLinkOurTeam", resourceCulture);
            }
        }
    }
}
