//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmitWinkel.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OurTeam {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurTeam() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmitWinkel.Resources.Home.OurTeam", typeof(OurTeam).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adele Lambrechts.
        /// </summary>
        public static string AuxilaryStaff1 {
            get {
                return ResourceManager.GetString("AuxilaryStaff1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melanie du Plessis.
        /// </summary>
        public static string AuxilaryStaff2 {
            get {
                return ResourceManager.GetString("AuxilaryStaff2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joléne Potgieter.
        /// </summary>
        public static string AuxilaryStaff3 {
            get {
                return ResourceManager.GetString("AuxilaryStaff3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elizabeth Williams.
        /// </summary>
        public static string AuxilaryStaff4 {
            get {
                return ResourceManager.GetString("AuxilaryStaff4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michelle Jejane.
        /// </summary>
        public static string AuxilaryStaff5 {
            get {
                return ResourceManager.GetString("AuxilaryStaff5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary Staff:.
        /// </summary>
        public static string AuxilaryStaffSubHeader {
            get {
                return ResourceManager.GetString("AuxilaryStaffSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentists:
        ///Dr Johan Smit
        ///Dr Richard Winkel
        ///Dr Finnie Kelly
        ///Dr Annetjie Smith
        ///Oral Hygienist:
        ///Christel Visagie
        ///Rozanne Marais
        ///Reception and Administration
        ///Jackie Kapp
        ///Sharon Sprong
        ///Christelle Smit
        ///Auxiliary Staff
        ///Adele Lambrechts
        ///Melanie du Plessis
        ///Joléne Potgieter
        ///Elizabeth Williams
        ///Michelle Jejane.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr Johan Smit.
        /// </summary>
        public static string Dentist1 {
            get {
                return ResourceManager.GetString("Dentist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr Richard Winkel.
        /// </summary>
        public static string Dentist2 {
            get {
                return ResourceManager.GetString("Dentist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr Finnie Kelly.
        /// </summary>
        public static string Dentist3 {
            get {
                return ResourceManager.GetString("Dentist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr Annetjie Smith.
        /// </summary>
        public static string Dentist4 {
            get {
                return ResourceManager.GetString("Dentist4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentists:.
        /// </summary>
        public static string DentistsSubHeader {
            get {
                return ResourceManager.GetString("DentistsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Staff.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christel Visagie.
        /// </summary>
        public static string OralHygienist1 {
            get {
                return ResourceManager.GetString("OralHygienist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozanne Marais.
        /// </summary>
        public static string OralHygienist2 {
            get {
                return ResourceManager.GetString("OralHygienist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral Hygienist:.
        /// </summary>
        public static string OralHygienistSubHeader {
            get {
                return ResourceManager.GetString("OralHygienistSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackie Kapp.
        /// </summary>
        public static string ReceptionAdmin1 {
            get {
                return ResourceManager.GetString("ReceptionAdmin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharon Sprong.
        /// </summary>
        public static string ReceptionAdmin2 {
            get {
                return ResourceManager.GetString("ReceptionAdmin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christelle Smit.
        /// </summary>
        public static string ReceptionAdmin3 {
            get {
                return ResourceManager.GetString("ReceptionAdmin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reception and Administration:.
        /// </summary>
        public static string ReceptionAdminSubHeader {
            get {
                return ResourceManager.GetString("ReceptionAdminSubHeader", resourceCulture);
            }
        }
    }
}
