//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmitWinkel.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PatientForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmitWinkel.Resources.Home.PatientForm", typeof(PatientForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIDS.
        /// </summary>
        public static string AIDS {
            get {
                return ResourceManager.GetString("AIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any allergies?.
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astma.
        /// </summary>
        public static string Astma {
            get {
                return ResourceManager.GetString("Astma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any bleeding tendencies or porphyria in family?.
        /// </summary>
        public static string Bleeding {
            get {
                return ResourceManager.GetString("Bleeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell nr (*).
        /// </summary>
        public static string CellNumber {
            get {
                return ResourceManager.GetString("CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Information Sheet
        ///PERSON RESPONSIBLE FOR ACCOUNT.
        ///Title	
        ///Initials (*)	
        ///Surname (*)	
        ///Physical Address	
        ///Postal Address	
        ///Home nr	
        ///Work nr	
        ///Cell nr (*)	
        ///Medical Aid	
        ///Medical Number	
        ///ID number	
        ///Occupation	
        ///Employer	
        ///E-mail (*)	
        ///Nearest Family/Friend name	
        ///(not from same address)
        ///Relationship	
        ///(not from same address)
        ///Next
        ///
        ///
        ///
        ///PLEASE SUPPLY THE FOLLOWING INFORMATION ABOUT THE PATIENT.
        ///Patient Surname	
        ///Full name	
        ///Date of birth	
        ///Patient ID number	
        ///Patient Occupation	
        ///Company	
        ///Ho [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronary Trombosis or cardiac disease.
        /// </summary>
        public static string CoronaryTrombosis {
            get {
                return ResourceManager.GetString("CoronaryTrombosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes.
        /// </summary>
        public static string Diabetes {
            get {
                return ResourceManager.GetString("Diabetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail (*).
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string Employer {
            get {
                return ResourceManager.GetString("Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Information Sheet.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepatitus.
        /// </summary>
        public static string Hepatitus {
            get {
                return ResourceManager.GetString("Hepatitus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home nr.
        /// </summary>
        public static string HomeNumber {
            get {
                return ResourceManager.GetString("HomeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypertension.
        /// </summary>
        public static string Hypertension {
            get {
                return ResourceManager.GetString("Hypertension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID number.
        /// </summary>
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initials (*).
        /// </summary>
        public static string Initials {
            get {
                return ResourceManager.GetString("Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kidney disease.
        /// </summary>
        public static string KidneyDisease {
            get {
                return ResourceManager.GetString("KidneyDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Aid.
        /// </summary>
        public static string MedicalAid {
            get {
                return ResourceManager.GetString("MedicalAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Number.
        /// </summary>
        public static string MedicalAidNumber {
            get {
                return ResourceManager.GetString("MedicalAidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you using any medication?.
        /// </summary>
        public static string Medication {
            get {
                return ResourceManager.GetString("Medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Family/Friend name.
        /// </summary>
        public static string NearestFamily {
            get {
                return ResourceManager.GetString("NearestFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not from same address).
        /// </summary>
        public static string NotFromSameAddress {
            get {
                return ResourceManager.GetString("NotFromSameAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you take treatment for Osteoporosis?.
        /// </summary>
        public static string Osteoporosis {
            get {
                return ResourceManager.GetString("Osteoporosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Cell Number.
        /// </summary>
        public static string PatientCellNumber {
            get {
                return ResourceManager.GetString("PatientCellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Company.
        /// </summary>
        public static string PatientCompany {
            get {
                return ResourceManager.GetString("PatientCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Date of Birth.
        /// </summary>
        public static string PatientDateOfBirth {
            get {
                return ResourceManager.GetString("PatientDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Full Name.
        /// </summary>
        public static string PatientFullName {
            get {
                return ResourceManager.GetString("PatientFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Home Language.
        /// </summary>
        public static string PatientHomeLanguage {
            get {
                return ResourceManager.GetString("PatientHomeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Home Number.
        /// </summary>
        public static string PatientHomeNumber {
            get {
                return ResourceManager.GetString("PatientHomeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID Number.
        /// </summary>
        public static string PatientIDNumber {
            get {
                return ResourceManager.GetString("PatientIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Marital Status.
        /// </summary>
        public static string PatientMaritalStatus {
            get {
                return ResourceManager.GetString("PatientMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Medical Dependant Number.
        /// </summary>
        public static string PatientMedicalDependantNumber {
            get {
                return ResourceManager.GetString("PatientMedicalDependantNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Occupation.
        /// </summary>
        public static string PatientOccupation {
            get {
                return ResourceManager.GetString("PatientOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Surname.
        /// </summary>
        public static string PatientSurname {
            get {
                return ResourceManager.GetString("PatientSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Work Number.
        /// </summary>
        public static string PatientWorkNumber {
            get {
                return ResourceManager.GetString("PatientWorkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Address.
        /// </summary>
        public static string PhysicalAddress {
            get {
                return ResourceManager.GetString("PhysicalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Address.
        /// </summary>
        public static string PostalAddress {
            get {
                return ResourceManager.GetString("PostalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If female, are you pregnant?.
        /// </summary>
        public static string Pregnant {
            get {
                return ResourceManager.GetString("Pregnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rheumatic fever.
        /// </summary>
        public static string Rheumatic {
            get {
                return ResourceManager.GetString("Rheumatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you smoke?.
        /// </summary>
        public static string Smoke {
            get {
                return ResourceManager.GetString("Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSON RESPONSIBLE FOR ACCOUNT..
        /// </summary>
        public static string SubHeader1 {
            get {
                return ResourceManager.GetString("SubHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE SUPPLY THE FOLLOWING INFORMATION ABOUT THE PATIENT..
        /// </summary>
        public static string SubHeader2 {
            get {
                return ResourceManager.GetString("SubHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you had any of the following diseases?.
        /// </summary>
        public static string SubHeader3 {
            get {
                return ResourceManager.GetString("SubHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname (*).
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work nr.
        /// </summary>
        public static string WorkNumber {
            get {
                return ResourceManager.GetString("WorkNumber", resourceCulture);
            }
        }
    }
}
