//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmitWinkel.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Services {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Services() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmitWinkel.Resources.Home.Services", typeof(Services).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restorative dentistry
        ///Aesthetic Dentistry
        ///Gumguards
        ///Implantology 
        ///Teeth whitening
        ///Conscious sedation
        ///Paediatric Dentistry         
        ///CAD-CAM – computerized dentistry (Cerec)     
        ///Root canal treatment
        ///Digital &amp; Panoramic Radiology
        ///Prosthodontics
        ///Oral hygiene.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restorative dentistry.
        /// </summary>
        public static string Service1 {
            get {
                return ResourceManager.GetString("Service1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital &amp; Panoramic Radiology.
        /// </summary>
        public static string Service10 {
            get {
                return ResourceManager.GetString("Service10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosthodontics.
        /// </summary>
        public static string Service11 {
            get {
                return ResourceManager.GetString("Service11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral hygiene.
        /// </summary>
        public static string Service12 {
            get {
                return ResourceManager.GetString("Service12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aesthetic Dentistry.
        /// </summary>
        public static string Service2 {
            get {
                return ResourceManager.GetString("Service2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gumguards.
        /// </summary>
        public static string Service3 {
            get {
                return ResourceManager.GetString("Service3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implantology.
        /// </summary>
        public static string Service4 {
            get {
                return ResourceManager.GetString("Service4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teeth whitening.
        /// </summary>
        public static string Service5 {
            get {
                return ResourceManager.GetString("Service5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conscious sedation.
        /// </summary>
        public static string Service6 {
            get {
                return ResourceManager.GetString("Service6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paediatric Dentistry.
        /// </summary>
        public static string Service7 {
            get {
                return ResourceManager.GetString("Service7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD-CAM – computerized dentistry (Cerec).
        /// </summary>
        public static string Service8 {
            get {
                return ResourceManager.GetString("Service8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root canal treatment.
        /// </summary>
        public static string Service9 {
            get {
                return ResourceManager.GetString("Service9", resourceCulture);
            }
        }
    }
}
